//
// Created by Tay on 6/11/2017.
//

#ifndef JIMP_EXERCISES_ACADEMIASEQUENTIALGENERATOR_H
#define JIMP_EXERCISES_ACADEMIASEQUENTIALGENERATOR_H

#endif //JIMP_EXERCISES_ACADEMIASEQUENTIALGENERATOR_H
